name: shared_widget_bottom_nav
description: A new Flutter project.
version: 1.0.0
author: pahlevikun
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  shared_manifest:
    path: ../../module_shared/shared_manifest
  shared_utilities:
    path: ../../module_shared/shared_utilities

flutter: